$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    responsiveClass:false,
    responsive:{
        0:{
            items:1,
            nav:false
        },
        600:{
            items:2,
            nav:false
        },
        1000:{
            items:5,
            nav:false,
            loop:true
        }
    }
})